### ISSUE TITLE
首页LOGO和账号字体样式的一些看法

### ISSUE THREAD

**Issue by tofrankie** [pancao/baidulite#10]
大佬您好，多谢大佬的Baidu Lite样式，跟原生相比实在简介好看很多。

在下有点强迫症，发现Baidu Lite有两个小Bug：

（1）百度首页，多出来一个白色的LOGO，很不协调，我的解决办法是：把id为lg下的img标签添加“! important”，增强优先级，因为不加的话，在调试器可以看出是被覆盖的，代码如下（大概在249行）： 
      #lg img { display: none !important; }

（2）还是百度首页，当登录百度账号之后，白色字体和灰色button背景不搭，于是我就把字体改成黑色的，会好看一点。在 .user-name 中添加：color: #000。完整代码（大概在1115行）：
.user-name {
      text-decoration: none !important;
      color: #000
}

**Comment by tofrankie** [comment]
所以是解决了吗？还是不解决？

**Comment by pancao** [comment]
更新了一版，不知道有没有解决，以后不会再维护了，可以自助修改～

**Comment by tofrankie** [comment]
好的
