### ISSUE TITLE
希望能够关闭搜索结果页面搜索框背景

### ISSUE THREAD

**Issue by 1235789gzy1** [pancao/baidulite#13]
我是多个样式一起使用的，希望能够关闭搜索结果页面，搜索框的背景
![image](https://user-images.githubusercontent.com/52618207/75517761-7376f400-5a3a-11ea-9f04-4524b3e554a1.png)

**Comment by pancao** [comment]
可以关的，在Customize Settings里面

**Comment by 1235789gzy1** [comment]
那不是连自定义背景也关闭了么？

> 可以关的，在自定义设置里面

**Comment by pancao** [comment]
本地编辑CSS，加一行这个就行了。线上版应该不会加这个功能。
```
#head .head_wrapper {
    background-image: none !important;
}
```
