### ISSUE TITLE
见图

### ISSUE THREAD

**Issue by mjkcyan** [pancao/baidulite#15]
<img width="960" alt="Snipaste_2020-04-11_12-08-14" src="https://user-images.githubusercontent.com/61610467/79035150-29169480-7bee-11ea-885f-93f05bb9e848.png">

**Comment by mjkcyan** [comment]
https://s1.ax1x.com/2020/04/11/GHuF6H.png

**Comment by pancao** [comment]
可以在安装页面选择启用极简模式并更新样式。
