### ISSUE TITLE
Safari 下失效的问题

### ISSUE THREAD

**Issue by akring** [pancao/baidulite#2]
在Safari下，首页没有问题，但是输入文字后点击搜索出现的结果页面，stylelist没有生效，chrome下一切正常，换用freestyler插件问题依旧，不知道是不是插件问题

**Comment by pancao** [comment]
这个应该是插件问题，很多 Safari 用户都反馈过。

**Comment by akring** [comment]
额，好吧，目前应该还没有解决方案吧？Google的stylelist貌似到是挺正常的

**Comment by pancao** [comment]
恩，只能等插件作者更新了。
