### ISSUE TITLE
字体发虚.

### ISSUE THREAD

**Issue by ghost** [pancao/baidulite#5]
问下为什么要改字体,在一些屏幕和系统下,改了字体会发虚.比如我的1600*900,替换了之后字体全部发虚.
而且夜间模式灰色字体颜色是否太暗?

**Comment by pancao** [comment]
字体问题：微软雅黑字体在大多数屏幕显示设备下体验比百度默认宋体更好，但是可能因为 Hinting 原因锐利度有时不够好，你可以选择在 css 中查找 `, "Microsoft Yahei UI"` 这些字符并替换成 ` ` 即可，后续可能会提供自定义字体选项。

夜间模式：对比度尚可。
