### ISSUE TITLE
新的搜索，会将样式全部重置回老版的样式

### ISSUE THREAD

**Issue by daoiqi** [pancao/baidulite#6]
新的关键字搜索，会将样式全部重置回老版的样式。

**Comment by pancao** [comment]
您是 Mac 下的 Safari 浏览器吗？

**Comment by daoiqi** [comment]
Windows 下的chrome55。 在网页下，按F5，会使用lite的样式。如果继续搜索，那就回到了百度原版了。

**Comment by pancao** [comment]
确实没有遇到过这样的情况，我没有办法复现。应该是插件的原因。

**Comment by coder30** [comment]
我也是遇到了同样的问题，在搜索栏在点击搜索的时候样式会消失

**Comment by pancao** [comment]
不能够复现这个 bug，还是倾向于 Stylish 插件的问题。

**Comment by coder30** [comment]
@pancao 我不是用Stylish 的，是用油猴安装的
